package org.example.network;
public enum RequestType {
    LOGIN,
    REGISTER,
    ADD_FRIEND,
    GET_FRIENDS,
    GET_FRIEND_REQUESTS,
    ACCEPT_FRIEND_REQUEST,
    DECLINE_FRIEND_REQUEST,
    SEARCH_USERS,
    GET_MY_WISH_LIST,
    CREATE_WISH_LIST,
    ADD_GIFT_ITEM,
    ADD_WISH_LIST_ITEM,
    REMOVE_WISH_LIST_ITEM,
    UPDATE_GIFT_ITEM,
    DELETE_GIFT_ITEM,

    ADD_NOTIFICATION,
    GET_NOTIFICATIONS,
    CLEAR_NOTIFICATIONS
}